config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :photos
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :image
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:image)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group" data-uppy="photo[image]">
    <%= form.label :image %>
    <div>
      <% if @photo.image.attached? %>
        <%= image_tag @photo.image, width: 280, data: { behavior: 'uppy-preview' } %>
      <% else %>
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSpj0DBTVsaja01_xWh37bcutvpd7rh7zEd528HD0d_l6A73osY" width="280" data-behavior="uppy-preview" />
      <% end %>
    </div>

    <%= link_to "Upload", "#", data: { behavior: "uppy-trigger" } %>
  </div>

  <div class="form-group">
    <% if photo.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', photo, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-primary' %>

    <% if photo.persisted? %>
      <%= link_to "Cancel", photo, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", photos_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Edit Photo</h1>

<%= render 'form', photo: @photo %>

app/views/photos/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Photos</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_photo_path, class: 'btn btn-primary' do %>
    Add New Photo
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    

            
          <th></th>
        
      </tr>
    </thead>

    <tbody>
      <% @photos.each do |photo| %>
        <%= content_tag :tr, id: dom_id(photo), class: dom_class(photo) do %>
          

          
          
            <td><%= link_to 'Show', photo %></td>
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form', photo: @photo %>

app/views/photos/show.html.erb
<div class="page-header">
  <%= link_to photos_path, class: 'btn btn-default' do %>
    All Photos
  <% end %>
  <%= link_to edit_photo_path(@photo), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show photo</h1>
</div>

<% if @photo.image.attached? %>
  <%= image_tag @photo.image %>
<% end %>